on:
  push:
    tags:
      - '*'

jobs:
  validate_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check tag format
        run: |
          TAG_NAME="$GITHUB_REF_NAME"

          if [[ ! "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Tag '$TAG_NAME' is not in correct format X.X.X!"
            exit 1
          fi
          echo "✅ Tag '$TAG_NAME' is valid."
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Check if tag is in master
        run: |
          TAG_COMMIT=$(git rev-list -n 1 "$GITHUB_REF") 

          if git branch -r --contains $TAG_COMMIT | grep -q 'origin/master'; then
            echo "✅ Tagged commit is in master branch"
          else
            echo "❌ Tagged commit is not in master branch, exiting..."
            exit 1
          fi

      - name: Start deploy task
        env:
          SEMAPHORE_ORG_URL: ${{ secrets.SEMAPHORE_CI_TOKEN }}
          SEMAPHORE_TASK_ID: ${{ secrets.SEMAPHORE_CI_TOKEN }}
          SEMAPHORE_CI_TOKEN: ${{ secrets.SEMAPHORE_CI_TOKEN }}
        run: |
          curl -X POST --location "https://${SEMAPHORE_ORG_URL}.semaphoreci.com/api/v1alpha/tasks/${SEMAPHORE_TASK_ID}/run_now" \
          -H "Authorization: Token ${SEMAPHORE_CI_TOKEN}" \
          -H "Content-Type: application/json" \
          -d '{"branch": "master", "pipeline_file": ".semaphore/semaphore.yml", "parameters": {"PAYOUT_PLUGIN_TAG": "'"$TAG_NAME"'"}}'
